version: '3'
services:
    noms-postgres:
        container_name: noms-postgres
        build: 
            context: ./postgres
        image: noms/postgres
        ports:
            - "5432:5432"
        volumes:
            - nomsvol:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=pass4admin

    noms-pgadmin:
        container_name: noms-pgadmin
        image: dpage/pgadmin4
        ports:
            - 80:80
        volumes:
            - nomsvol:/var/lib/pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=noms@siemens.com
            - PGADMIN_DEFAULT_PASSWORD=pass4root
        
    noms-rabbitmq:
        container_name: noms-rabbitmq
        build: 
            context: ./rabbitmq
        image: noms/rabbitmq
        ports:
            - 15672:15672
        volumes:
            - nomsvol:/var/lib/rabbitmq
            
    noms-redis:
        container_name: noms-redis
        image: redis
        ports:
            - 6379:6379
        volumes:
            - nomsvol:/data

    noms-om:
        container_name: noms-om
        build: 
            context: ./outage-management
            args:
                url: git@code.siemens.com:halil.ayyildiz/noms.git
                project: outage-management
                artifactid: noms-om
                version: 0.0.1
        image: noms/outage-management
        ports:
            - 8080:8080
        volumes:
            - nomsvol:/root/.m2

    noms-topotr:
        container_name: noms-topotr
        build: 
            context: ./topo-tracer
            args:
                url: git@code.siemens.com:halil.ayyildiz/noms.git
                project: topo-tracer
                artifactid: noms-topotr
                version: 0.0.1
        image: noms/topo-tracer
        ports:
            - 8081:8080
        volumes:
            - nomsvol:/root/.m2
            
volumes:
  nomsvol: