apiVersion: apps/v1
kind: Deployment
metadata:
  name: dply-outage-management
spec:
  selector:
    matchLabels:
      app: outage-management
  replicas: 3
  template:
    metadata:
      labels:
        app: outage-management
    spec:
      containers:
      - name: outage-management
        image: 35.156.234.183:5000/noms/outage-management:0.0.1
        ports:
        - containerPort: 8080