apiVersion: v1
kind: Service
metadata:
  name: outage-management-service
  labels:
    app: outage-management
spec:
  type: NodePort
  ports: 
  - port: 8080
    protocol: TCP
  selector:
    app: outage-management